add new chart hel-controller
quortex/helm-charts pull request #13
Opened 2022-08-23 12:43 UTC by HansCeril

add makefile
forgot makefile
add templated variables
add roles clusterroles rolebinding clusterrolebinding serviceaccount
correction

2022-08-23 12:54 UTC, swbsf commented on .vscode/configurationCache.log
> +{"buildTargets":[],"launchTargets":[],"customConfigurationProvider":{"workspaceBrowse":{"browsePath":[],"compilerArgs":[]},"fileIndex":[]}}
.vscode folder should be in .gitignore

2022-08-23 12:54 UTC, swbsf commented on .vscode/settings.json
> +{
.vscode folder should be in .gitignore

2022-08-23 12:54 UTC, swbsf commented on .vscode/targets.log
> +make: *** No rule to make target 'all'.  Stop.
.vscode folder should be in .gitignore

2022-08-23 12:54 UTC, swbsf commented on charts/helm-controller-operator/values.yaml
> +    - 10.96.163.142
Maybe set your IDE to add last line on save?

2022-08-23 12:54 UTC, swbsf commented on charts/helm-controller-operator/templates/roles.yaml
> +  - delete
Maybe set your IDE to add last line?

2022-08-23 12:54 UTC, swbsf commented on charts/helm-controller-operator/Makefile
> +	@curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- "4.4.1" "$$(go env GOPATH)/bin"
Maybe move the version to a global variable ?

2022-08-23 13:25 UTC, vincentmrg commented on charts/helm-controller-operator/Chart.yaml
> +description: A Helm chart for Kubernetes
A better description would be nice!

2022-08-23 13:26 UTC, vincentmrg commented on charts/helm-controller-operator/Makefile
> +KUSTOMIZE=$(shell which kustomize)
```suggestion
KUSTOMIZE=$(shell which kustomize)

```

2022-08-23 13:32 UTC, antonincms commented on charts/helm-controller-operator/templates/cluster_roles_bidings.yaml
> +  name: helm-manager-rolebinding
```suggestion
  name: {{ include "helm-manager.fullname" . }}-rolebinding
```

2022-08-23 13:35 UTC, antonincms commented on charts/helm-controller-operator/templates/deployment.yaml
> +        prometheus.io/scrape: "true"
Should not be hardcoded
```suggestion
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2022-08-23 13:36 UTC, antonincms commented on charts/helm-controller-operator/templates/deployment.yaml
> +        app: helm-controller
Cf : use the function from the tpl generated by helm
```suggestion
      labels:
        {{- include "helm-controller-operator.selectorLabels" . | nindent 8 }}
```

2022-08-24 09:18 UTC, antonincms commented on charts/helm-controller-operator/templates/deployment.yaml
> +        image: "{{ .repository }}:{{ .tag }}"
```suggestion
        image: "{{ .repository }}:{{ {{ .tag | default $.Chart.AppVersion }} }}"
```

2022-08-24 09:24 UTC, antonincms commented on charts/helm-controller-operator/templates/deployment.yaml
> +        terminationMessagePolicy: File
```suggestion
```

2022-08-24 09:24 UTC, antonincms commented on charts/helm-controller-operator/templates/deployment.yaml
> +      schedulerName: default-scheduler
```suggestion
```

2022-08-24 09:27 UTC, antonincms commented on charts/helm-controller-operator/templates/deployment.yaml
> +      terminationGracePeriodSeconds: 600
```suggestion
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
```

2022-08-25 08:41 UTC, antonincms requested changes

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/templates/helmController/service.yaml
> +    {{- include "helm-controller-operator.selectorLabels" . | nindent 4 }}
When you describe this service do you see all its pods in the status or pods from the sourceController as well ?
Hmm I think you should have different selector labels for the two deployment, e.g. by adding `app.kubernetes.io/component: helm-controller` to labels and selectors (e.g. as the [chart we saw does](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/querier/_helpers-querier.tpl))

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +    - 10.96.163.142
```suggestion
```

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/templates/sourceController/service.yaml
> +  ipFamilyPolicy: SingleStack
All of this is not needed : 
* clusterIP are automatically filled
* internalTrafficPolicy / ipFamilies / ipFamilyPolicy are at their default values. 

You should compare what helm template and the kustomize produces, I'm sure theses were not there.

```suggestion
```

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/templates/sourceController/service.yaml
> +  sessionAffinity: None
```suggestion
```

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +    revisionHistoryLimit: 10
What are these ? I don't see where they are used.

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +        memory: 64Mi
No resources by default (and resources takes one s)
```suggestion
    resources: {}
    #  limits:
    #    cpu: "1"
    #    memory: 1Gi
    #  requests:
    #    cpu: 100m
    #    memory: 64Mi
```

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/templates/helmController/deployment.yaml
> +          {{- toYaml .ressources | nindent 10 }}
```suggestion
          {{- toYaml .resources | nindent 10 }}
```

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +    revisionHistoryLimit: 10
Idem, what is this

2022-08-25 08:41 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +        memory: 64Mi
```suggestion
    resources:
    #  limits:
    #    cpu: "1"
    #    memory: 1Gi
    #  requests:
    #    cpu: 50m
    #    memory: 64Mi
```

2022-08-25 10:03 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +    - 10.96.163.142
You did not resolve this issue yet

2022-08-25 10:04 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +    - 10.96.163.142
Service should be specific to either one. Furthermore clusterIps is not needed and type is not used.
```suggestion
```

2022-08-25 10:06 UTC, antonincms commented on charts/helm-controller-operator/templates/helmController/_helpers-helm-controller.tpl
> +{{- end }}
```suggestion
{{/*
helm-controller fullname
*/}}
{{- define "helm-controller-operator.helmControllerFullname" -}}
{{ include "helm-controller-operator.fullname" . }}-helm
{{- end }}

{{/*
helm-controller common labels
*/}}
{{- define "helm-controller-operator.helmControllerLabels" -}}
{{ include "helm-controller-operator.labels" . }}
app.kubernetes.io/component: helm-controller
{{- end }}

{{/*
helm-controller selector labels
*/}}
{{- define "helm-controller-operator.helmControllerSelectorLabels" -}}
{{ include "helm-controller-operator.selectorLabels" . }}
app.kubernetes.io/component: helm-controller
{{- end }}
```

2022-08-25 10:07 UTC, antonincms commented on charts/helm-controller-operator/templates/sourceController/_helpers-source-controller.tpl
> +{{- end }}
```suggestion
{{/*
source-controller fullname
*/}}
{{- define "helm-controller-operator.sourceControllerFullname" -}}
{{ include "helm-controller-operator.fullname" . }}-source
{{- end }}

{{/*
source-controller common labels
*/}}
{{- define "helm-controller-operator.sourceControllerLabels" -}}
{{ include "helm-controller-operator.labels" . }}
app.kubernetes.io/component: source-controller
{{- end }}

{{/*
source-controller selector labels
*/}}
{{- define "helm-controller-operator.sourceControllerSelectorLabels" -}}
{{ include "helm-controller-operator.selectorLabels" . }}
app.kubernetes.io/component: source-controller
{{- end }}
```

2022-08-25 10:09 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +# -- ****** Value for the helm-controller *******
```suggestion
# ****** Value for the helm-controller *******
```

2022-08-25 10:10 UTC, antonincms commented on charts/helm-controller-operator/values.yaml
> +# -- ****** Value for the source-controller *******
-- are made to document individual values

```suggestion
# Value for the source-controller
```

2022-08-29 15:03 UTC, vincentmrg commented on charts/helm-controller-stack/Chart.yaml
> +appVersion: "1.16.0"
Seems there is no app version
```suggestion
```

2022-08-29 15:08 UTC, vincentmrg commented on charts/helm-controller-stack/templates/sourceController/service.yaml
> +
```suggestion
```

2022-08-29 15:11 UTC, vincentmrg commented on charts/helm-controller-stack/values.yaml
> +    podAnnotations: {}
duplicate, which one is used ?

2022-08-29 15:13 UTC, vincentmrg commented on charts/helm-controller-stack/README.md
> +Have a look on official documentation [Using Helm Operator in Kubernetes clusters](https://github.com/fluxcd/helm-controller)
The description of this chart is quite minimal, a short paragraph explaining what it is, with a link to the flux repository might be relevant here.

2022-08-29 16:19 UTC, vincentmrg commented on charts/helm-controller-stack/Chart.yaml
> +description: A Helm controller operator chart for Kubernetes allowing one to declaratively manage Helm chart releases
```suggestion
description: A Helm controller chart for Kubernetes allowing one to declaratively manage Helm chart releases
```

2022-08-30 08:28 UTC, antonincms commented on charts/helm-controller-stack/templates/helmController/deployment.yaml
> +        - --enable-leader-election
You don't use the extraArgs present in values ?

2022-08-30 08:28 UTC, antonincms commented on charts/helm-controller-stack/templates/sourceController/deployment.yaml
> +        - --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.
Idem, you should add an extraArgs

2022-08-30 09:34 UTC, antonincms approved these changes

2022-08-30 09:53 UTC, merged